/******************************************************************************
 *
 * [Module]: HC-SR04
 *
 * [File Name]: ultrasonic.c
 *
 * [Description]: Source file for the AVR HC-SR04 driver
 *
 * [Author]: Mahmoud Khaled
 *
 *******************************************************************************/

#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include <util/delay.h>

/************************************************************************
 * 								Global Variables						*
 ************************************************************************/
uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;

/************************************************************************
 * 								Configuration							*
 ************************************************************************/
Icu_ConfigType Icu_Config = {F_CPU_8, RISING};



/************************************************************************
 * 							Functions Definitions						*
 ************************************************************************/
/*
 * Description:
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{

	/*Initialize the ICU driver as required*/
	Icu_init(&Icu_Config);

	/*Setup the ICU call back function*/
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	/*Setup the direction for the trigger pin as output pin through the GPIO driver*/
	GPIO_setupPinDirection(PORTB_ID, PIN5_ID, PIN_OUTPUT);
}



/*
 * Description:
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_HIGH);

	_delay_us(10);

	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_LOW);
}


/*
Description
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 * Inputs: None
 * Return: The measured distance in Centimeter.
 */
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance;

	/*Send the trigger pulse by using Ultrasonic_Trigger function*/
	Ultrasonic_Trigger();

	/*Measured distance in Centimeter*/
	distance = g_timeHigh/57.9;

	return distance;
}


/*
 * Description:
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect the Falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
		g_edgeCount = 0;
		Icu_clearTimerValue();
	}
}
